### PR TITLE
Upgrade build tools

### PR DESCRIPTION
**Pull request by noordawod**
Rosetta is a fine piece of code and I'd love keep it alive and updated. However, the build tools used in this project are outdated and Rosetta no longer generates code due to errors when running build runner.

This pr bumps up the versions of the build tools used so that it runs with most recent versions.

### CODE REVIEW

**Comment by noordawod** [comment]
Anybody?

**Comment by noordawod** [comment]
Is it safe to say this is a dead project?

**Comment by remcoanker** [comment]
I think this package is abandoned. A shame, since this is the only one I've found that can do both autocompletion and runtime loading of dynamic translations.

I've made similar fixes like yours to keep it running in our project. It would be great if someone could take over this project.

**Comment by noordawod** [comment]
I was in touch in TeamWanari actually and they said that they had a lot of pressure at this time, and that they aren't abandoning this project. That was, I believe, 2-3 months ago... I am tending to think that they just don't have time and that this project has no time allocation in their schedule.

Anyway, I may just clone it and add it to pub.dev on my own.

**Comment by noordawod** [comment]
@RenatoKiss @agta1991 @talamaska @csbence10 @RobiWanari @l4ty4k @pogiedoge 
Happy holidays TeamWanari! Maybe the new year will bring good news to this repo? :)

**Comment by talamaska** [comment]
I suggest you pinging the team in twitter and via email. I had pushed previously some fixes with quite heavy pushing on my side. It feels the project needs to be forked and released under different name, like Rosetta2 or something. Also it seems no null-safe migration was ever made. Btw I migrated to the official Flutter internationalization method.

**Comment by noordawod** [comment]
> I suggest you pinging the team in twitter and via email. I had pushed previously some fixes with quite heavy pushing on my side. It feels the project needs to be forked and released under different name, like Rosetta2 or something. Also it seems no null-safe migration was ever made. Btw I migrated to the official Flutter internationalization method.

Maybe a good idea. Link to official i16n method please?

**Comment by talamaska** [comment]
https://docs.flutter.dev/development/accessibility-and-localization/internationalization

**Comment by noordawod** [comment]
Thanks @talamaska for the tip, I have now switched to the official localization method and it works very well. I've given up on Rosetta's team so my pr is closed.

**Pull request closed without merging**
