### PR TITLE
Add support for all locales that contains scriptCode and countryCode

### PR DESCRIPTION
**Pull request by TabooSun**
### Introduction
Flutter's localization supports locale with different scriptCode and countryCode.
[Detail](https://api.flutter.dev/flutter/widgets/WidgetsApp/supportedLocales.html) can be found here.

### Work Done
From the parameter: locale, get the scriptCode and countryCode from it. Check if these 2 properties exist and add it to a local variable if it does not.

### CODE REVIEW

**Comment by noordawod** [comment]
@TabooSun any chance you can fix the conflicts?

**Comment by TabooSun** [comment]
I am not using this package anymore, I can try to resolve the conflict this weekend.

**Comment by noordawod** [comment]
> I am not using this package anymore, I can try to resolve the conflict this weekend.

Thank you!

Out of interest, may I ask what package are you using now?

**Comment by TabooSun** [comment]
Not using any.

**Comment by TabooSun** [comment]
I have tried to merge the development branch into my working branch. However, I am facing issue testing.

I got this error when trying to run `flutter packages pub run build_runner build`

```

Exhausted heap space, trying to allocate 34320316384 bytes.


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


Out of Memory
dart:core                                                       new _List
package:analyzer/src/summary/flat_buffers.dart 819:20           _FbGenericList.[]
package:analyzer/src/summary/package_bundle_reader.dart 431:44  SummaryDataStore.addBundle
package:analyzer/src/dart/sdk/sdk.dart 94:21                    AbstractDartSdk.context
package:analyzer/src/context/context.dart 1884:46               PartitionManager.forSdk
package:analyzer/src/context/context.dart 681:50                AnalysisContextImpl.createCacheFromSourceFactory.createCache
package:analyzer/src/context/context.dart 686:38                AnalysisContextImpl.createCacheFromSourceFactory
package:analyzer/src/context/context.dart 413:14                AnalysisContextImpl.sourceFactory=
package:build_resolvers/src/resolver.dart 95:14                 new AnalyzerResolver
package:build_resolvers/src/resolver.dart 449:32                new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 136:19      BuildOptions.create
dart:async                                                      _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart   TargetGraph.forPackageGraph
dart:async                                                      _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart   _packageBuildConfig
dart:async                                                      _completeOnAsyncReturn
package:build_config/src/build_config.dart                      BuildConfig.fromBuildConfigDir

pub finished with exit code 1

```

**Pull request closed without merging**
